runtime: nodejs16
env: standard

# Specify the start command for the app
entrypoint: npm run start

# The app will be served from the build folder
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
