runtime: nodejs16
env: standard

# Specify the start command for the app
entrypoint: npm run start

# The app will be served from the build folder
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
